name: pypi

on:
  release:
    types: [published]
  pull_request:
    branches: [ main ]

jobs:
  pyping:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - if: ${{ github.event.action == 'published' }}
      name: Publish package
      uses: pypa/gh-action-pypi-publish@a3a3bafbb3e5a75a854ae1bc53ae128cf22c4af4
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
